# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/johba/digital_hardware_design/lecture7/exercise3/exercise3.srcs/sources_1/bd/top_traffic_design/ip/top_traffic_design_c_counter_binary_0_0/top_traffic_design_c_counter_binary_0_0.xci
# IP: The module: 'top_traffic_design_c_counter_binary_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/johba/digital_hardware_design/lecture7/exercise3/exercise3.gen/sources_1/bd/top_traffic_design/ip/top_traffic_design_c_counter_binary_0_0/top_traffic_design_c_counter_binary_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_traffic_design_c_counter_binary_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/johba/digital_hardware_design/lecture7/exercise3/exercise3.srcs/sources_1/bd/top_traffic_design/ip/top_traffic_design_c_counter_binary_0_0/top_traffic_design_c_counter_binary_0_0.xci
# IP: The module: 'top_traffic_design_c_counter_binary_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/johba/digital_hardware_design/lecture7/exercise3/exercise3.gen/sources_1/bd/top_traffic_design/ip/top_traffic_design_c_counter_binary_0_0/top_traffic_design_c_counter_binary_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_traffic_design_c_counter_binary_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
