set_property PACKAGE_PIN L17 [get_ports clk]
set_property PACKAGE_PIN U5 [get_ports green]
set_property PACKAGE_PIN V8 [get_ports red]
set_property PACKAGE_PIN U7 [get_ports yellow]
set_property IOSTANDARD LVCMOS33 [get_ports green]
set_property IOSTANDARD LVCMOS33 [get_ports red]
set_property IOSTANDARD LVCMOS33 [get_ports yellow]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
