set_property IOSTANDARD LVCMOS33 [get_ports {inp[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inp[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inp[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inp[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outp[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outp[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outp[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outp[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports RE]
set_property IOSTANDARD LVCMOS33 [get_ports WE]
set_property PACKAGE_PIN L3 [get_ports {inp[0]}]
set_property PACKAGE_PIN A16 [get_ports {inp[1]}]
set_property PACKAGE_PIN K3 [get_ports {inp[2]}]
set_property PACKAGE_PIN C15 [get_ports {inp[3]}]
set_property PACKAGE_PIN U5 [get_ports {outp[0]}]
set_property PACKAGE_PIN U2 [get_ports {outp[1]}]
set_property PACKAGE_PIN W6 [get_ports {outp[2]}]
set_property PACKAGE_PIN U3 [get_ports {outp[3]}]
set_property PACKAGE_PIN A18 [get_ports RE]
set_property PACKAGE_PIN B18 [get_ports WE]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets WE_IBUF]

set_property PULLDOWN true [get_ports {inp[3]}]
set_property PULLDOWN true [get_ports {inp[2]}]
set_property PULLDOWN true [get_ports {inp[1]}]
set_property PULLDOWN true [get_ports {inp[0]}]
