set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports D]
set_property PACKAGE_PIN B18 [get_ports D]
set_property PACKAGE_PIN A17 [get_ports {LED[0]}]
set_property PACKAGE_PIN C16 [get_ports {LED[1]}]
set_property PACKAGE_PIN C17 [get_ports {LED[2]}]
set_property PACKAGE_PIN B16 [get_ports {LED[3]}]

set_property PACKAGE_PIN A18 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]