# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/top_traffic_design/top_traffic_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_traffic_design || ORIG_REF_NAME==top_traffic_design} -quiet] -quiet

# IP: bd/top_traffic_design/ip/top_traffic_design_c_counter_binary_0_0/top_traffic_design_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_traffic_design_c_counter_binary_0_0 || ORIG_REF_NAME==top_traffic_design_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/top_traffic_design/ip/top_traffic_design_top_0_0/top_traffic_design_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_traffic_design_top_0_0 || ORIG_REF_NAME==top_traffic_design_top_0_0} -quiet] -quiet

# IP: bd/top_traffic_design/ip/top_traffic_design_xlslice_0_0/top_traffic_design_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_traffic_design_xlslice_0_0 || ORIG_REF_NAME==top_traffic_design_xlslice_0_0} -quiet] -quiet

# XDC: c:/Users/johba/digital_hardware_design/lecture7/exercise3/exercise3.gen/sources_1/bd/top_traffic_design/top_traffic_design_ooc.xdc
